### ISSUE TITLE
Just for future reference

### ISSUE THREAD

**Issue by costis-t** [99991/parallel-md5sum#1]
Likely not worth look into those, because they seem very rare corner cases. But if it happens again to my syncs, I'll solve them.

 ```
Traceback (most recent call last):
  File "<censored>/./md5sum", line 119, in <module>
    main()
  File "<censored>/./md5sum", line 21, in main
    check_checksums(args.method, args.check, name)
  File "<censored>/../md5sum", line 62, in __init__
    lines = f.readlines()
            ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 4421-4422: invalid continuation byte
```
and
```
Traceback (most recent call last):
  File "<censored>/./md5sum", line 128, in <module>
    main()
  File "<censored>/./md5sum", line 21, in main
    check_checksums(args.method, args.check, name)
  File "<censored>/./md5sum", line 74, in __init__
    for stdout, stderr in pool.imap(self.check_checksum, lines):
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "<censored>/./md5sum", line 99, in check_checksum
    checksum, filename = line.rstrip("\n").split(maxsplit=1)
    ^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

For now, I just replace
 https://github.com/99991/parallel-md5sum/blob/ecd1467ac4a22421b7b86073e1ce919e5ba0a6b5/md5sum#L61 with
`        with open(checksum_filename, errors='ignore') as f:
`

and

https://github.com/99991/parallel-md5sum/blob/ecd1467ac4a22421b7b86073e1ce919e5ba0a6b5/md5sum#L90 with
```python
        try:
            checksum, filename = line.rstrip("\n").split(maxsplit=1)
        except ValueError:
            pass
```

**Comment by 99991** [comment]
The checksum file probably contains text which is not using UTF-8 encoding, but uses some other encoding instead. Could you run `file -i <your_checksums.txt>` to check?

If that is the case, you can try converting your checksum file to UTF-8 encoding like so:

```
iconv -f <old_encoding> -t utf-8 <your_checksums.txt> -o <your_checksums_utf-8.txt>
```
